// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veterinaria.API.Data;

#nullable disable

namespace Veterinaria.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240325015226_EntitiesFullWithAgenda")]
    partial class EntitiesFullWithAgenda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Veterinaria.Shared.Entities.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("OwnersId")
                        .HasColumnType("int");

                    b.Property<int?>("PetsId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnersId");

                    b.HasIndex("PetsId");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("Veterinaria.Shared.Entities.History", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PetsId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServiceTypesid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PetsId");

                    b.HasIndex("ServiceTypesid");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("Veterinaria.Shared.Entities.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FixedPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Veterinaria.Shared.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Born")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OwnersId")
                        .HasColumnType("int");

                    b.Property<int?>("PetTypesid")
                        .HasColumnType("int");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnersId");

                    b.HasIndex("PetTypesid");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Veterinaria.Shared.Entities.PetType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.ToTable("PetTypes");
                });

            modelBuilder.Entity("Veterinaria.Shared.Entities.ServiceType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("Veterinaria.Shared.Entities.Agenda", b =>
                {
                    b.HasOne("Veterinaria.Shared.Entities.Owner", "Owners")
                        .WithMany("Agendas")
                        .HasForeignKey("OwnersId");

                    b.HasOne("Veterinaria.Shared.Entities.Pet", "Pets")
                        .WithMany("Agendas")
                        .HasForeignKey("PetsId");

                    b.Navigation("Owners");

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("Veterinaria.Shared.Entities.History", b =>
                {
                    b.HasOne("Veterinaria.Shared.Entities.Pet", "Pets")
                        .WithMany("Histories")
                        .HasForeignKey("PetsId");

                    b.HasOne("Veterinaria.Shared.Entities.ServiceType", "ServiceTypes")
                        .WithMany("Histories")
                        .HasForeignKey("ServiceTypesid");

                    b.Navigation("Pets");

                    b.Navigation("ServiceTypes");
                });

            modelBuilder.Entity("Veterinaria.Shared.Entities.Pet", b =>
                {
                    b.HasOne("Veterinaria.Shared.Entities.Owner", "Owners")
                        .WithMany()
                        .HasForeignKey("OwnersId");

                    b.HasOne("Veterinaria.Shared.Entities.PetType", "PetTypes")
                        .WithMany()
                        .HasForeignKey("PetTypesid");

                    b.Navigation("Owners");

                    b.Navigation("PetTypes");
                });

            modelBuilder.Entity("Veterinaria.Shared.Entities.Owner", b =>
                {
                    b.Navigation("Agendas");
                });

            modelBuilder.Entity("Veterinaria.Shared.Entities.Pet", b =>
                {
                    b.Navigation("Agendas");

                    b.Navigation("Histories");
                });

            modelBuilder.Entity("Veterinaria.Shared.Entities.ServiceType", b =>
                {
                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
